# Generated by Django 2.2.10 on 2020-02-18 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dining', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dining',
            name='file_upload',
            field=models.FileField(default='', upload_to='dining/images'),
        ),
    ]
