# Generated by Django 2.2.10 on 2020-02-18 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dining', '0002_dining_file_upload'),
    ]

    operations = [
        migrations.AddField(
            model_name='dining',
            name='images_upload',
            field=models.ImageField(default='', upload_to='dining/files'),
        ),
    ]
