# Generated by Django 2.2.10 on 2020-02-18 13:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Dining', '0003_dining_images_upload'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dining',
            name='images_upload',
        ),
        migrations.AlterField(
            model_name='dining',
            name='file_upload',
            field=models.FileField(default='', upload_to='dining/files'),
        ),
        migrations.CreateModel(
            name='Dinigimage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images_upload', models.ImageField(default='', upload_to='dining/files')),
                ('dining', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dining', to='Dining.Dining')),
            ],
        ),
    ]
