# Generated by Django 3.0.3 on 2020-02-19 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dining', '0004_auto_20200218_1842'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dinigimage',
            name='images_upload',
            field=models.ImageField(default='', upload_to='dining/images'),
        ),
    ]
