# Generated by Django 3.0.3 on 2020-02-20 05:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Dining', '0005_auto_20200219_1305'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Dinigimage',
            new_name='Restaurants_images',
        ),
    ]
