# Generated by Django 3.0.3 on 2020-02-20 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dining', '0006_auto_20200220_1109'),
    ]

    operations = [
        migrations.CreateModel(
            name='VendorsRestaurant_search',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Rating', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], max_length=200)),
                ('City', models.CharField(choices=[('mumbai', 'Mumbai'), ('delhi', 'Delhi'), ('Bangalore', 'Bangalore'), ('Hyderabad', 'Hyderabad'), ('Ahmedabad', 'Ahmedabad')], max_length=200)),
                ('Area', models.CharField(choices=[('andheri', 'Aandheri'), ('malad', 'Malad'), ('marol', 'Marol'), ('chembure', 'Chembure'), ('vashi', 'Vashi')], max_length=200)),
                ('Cuisines', models.CharField(choices=[('Thai', 'Thai'), ('Tea ', 'Tea'), ('Spanish ', 'Spanish'), ('Indian', 'Indian'), ('seafood', 'seafood')], max_length=200)),
            ],
        ),
    ]
