# Generated by Django 3.0.3 on 2020-02-20 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dining', '0007_vendorsrestaurant_search'),
    ]

    operations = [
        migrations.AddField(
            model_name='dining',
            name='is_staff',
            field=models.BooleanField(default=False, verbose_name='Search from Database'),
        ),
    ]
