# Generated by Django 3.0.3 on 2020-02-20 09:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Dining', '0008_dining_is_staff'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dining',
            name='is_staff',
        ),
    ]
