# Generated by Django 2.2.10 on 2020-03-09 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dining', '0009_remove_dining_is_staff'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dining',
            name='State',
            field=models.CharField(choices=[('Andhra Pradesh', 'Andhra Pradesh'), ('Assam ', 'Assam'), ('Bihar ', 'Bihar'), ('Goa', 'Goa'), ('Gujarat', 'Gujarat'), ('Maharashtra', 'Maharashtra')], max_length=200),
        ),
    ]
