# Generated by Django 2.2.10 on 2020-03-23 13:07

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('airportlounge', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='airportlounge',
            name='Facilities',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('WIFI', 'WIFI'), ('Food', 'Food'), ('Alcohol', 'Alcohol'), ('Shower', 'Shower'), ('Sleeping Pod', 'Sleeping Pod')], max_length=37),
        ),
    ]
