# Generated by Django 2.2.10 on 2020-03-24 13:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('airportlounge', '0005_auto_20200324_1424'),
    ]

    operations = [
        migrations.CreateModel(
            name='PackageDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Package_Details', models.TextField(default='', max_length=100)),
                ('airportlounge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='airport', to='airportlounge.AirportLounge')),
            ],
        ),
    ]
