# Generated by Django 2.2.10 on 2020-03-30 14:35

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bus_Booking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name_of_Bus', models.CharField(max_length=100)),
                ('From_City', models.CharField(choices=[('mumbai', 'Mumbai'), ('delhi', 'Delhi'), ('Bangalore', 'Bangalore'), ('Hyderabad', 'Hyderabad'), ('Ahmedabad', 'Ahmedabad')], max_length=200)),
                ('To_City', models.CharField(choices=[('mumbai', 'Mumbai'), ('delhi', 'Delhi'), ('Bangalore', 'Bangalore'), ('Hyderabad', 'Hyderabad'), ('Ahmedabad', 'Ahmedabad')], max_length=200)),
                ('Bus_Type', models.CharField(choices=[('Non AC Seater ', 'Non AC Seater '), ('Non AC Sleeper', 'Non AC Sleeper'), ('AC Seater', 'AC Seater'), ('AC Sleeper', 'AC Sleeper')], max_length=200)),
                ('Facilities', multiselectfield.db.fields.MultiSelectField(choices=[('WIFI', 'WIFI'), ('Food', 'Food'), ('Alcohol', 'Alcohol'), ('Shower', 'Shower'), ('Sleeping Pod', 'Sleeping Pod')], max_length=37)),
                ('Service_Range', models.CharField(choices=[('India', 'India'), ('International', 'International')], max_length=10)),
                ('Days_of_Operations', models.CharField(choices=[('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday'), ('Saturday', 'Saturday'), ('Sunday', 'Sunday')], max_length=200)),
                ('Depature_Time', models.TimeField()),
                ('Arrival_Time', models.TimeField()),
                ('Rating', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], max_length=200)),
                ('Ticket_Amount_Per_Passenger', models.CharField(max_length=100)),
                ('Brief_Over_Facilities', models.TextField(max_length=500)),
                ('Travel_Agency', models.CharField(max_length=100)),
                ('Status', models.IntegerField(choices=[(0, 'Inactive'), (1, 'Active')], default=0)),
                ('AddedOn', models.DateField()),
            ],
        ),
    ]
