# Generated by Django 2.2.10 on 2020-03-30 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Bus_Booking_main', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Bus_Booking',
            new_name='BusBooking',
        ),
    ]
